### ISSUE TITLE
Great tool, I'd like to add on to it if possible!

### ISSUE THREAD

**Issue by tconboy** [Sanghera/RGP-Gen#1]
I'm interested in trying to use this for other fluids.  I wanted to try to edit the fluid and re-compile, or add a user option for fluid choice, but I get some errors.  Would it be possible to supply some instructions on how you compiled the .exe?  

I suppose I could rename any fluid I want to 'co2.fld', but not very elegant :)

**Comment by sangheraio** [comment]
Yeah, it should definitely be possible to use it for different fluids.  Your solution would probably work, all you have to do is make sure you change the .fld fluid file to CO2.  The more elegant way would be to do just add another READ() and a bunch of cases based on the user input which change lines 58,59,69,125,130,132, and 134 with the correct names/files.  This is done in the TurboGasProps repo if you want to have a look at how it is done exactly.

For compilation I would recommend downloading a free trial of Simply Fortran, open the .f90 file, save it as a project, and click the build button (http://simplyfortran.com/).

Let me know if you have any other questions, good luck!

**Comment by tconboy** [comment]
Sanghera,
Thanks for your quick response. Yes I did try to just compile it directly with a fortran compiler, also tried again with Simply Fortran.  But it fails with a number of errors, so I guess I'm missing something-- I'm definitely not an experienced programmer.  Does it point to any of the Refprop fortran files?  If so, do they need specific directory path with respect to your file?  
Tom

**Comment by sangheraio** [comment]
Ah right, sorry it's been a while since I made this... Yes you will need to obtain the REFPROP subroutines in order to re-compile it successfully.  They come along with the purchase of NIST REFPROP (version 8 or 9 will work).

**Comment by MOdabaee** [comment]
Thanks for the code.
I have access to REFPROP 9. Would you let me know how I can create "fluids(folder) - Includes REFPROP fluids needed for generating the rgp file Source Code(folder)"? Or if you could send me a sample ?

**Comment by sangheraio** [comment]
No problem! There should be a fluids folder in your REFPROP installation folder. Just copy and paste that folder into your working directory and run the executable.  If that doesn't work you might need to recompile it with your fluids folder added to the FORTRAN project directory.

**Comment by MOdabaee** [comment]
Thanks for your prompt reply.
It works now and generates the table.
Would you please have a look at the attached file? In both table 1 (enthalpy) and table 2 (entropy) data are missed and replaced by  “NAN”. I double checked with REFPROP there values for the required temperature and pressure range. I really appreciate if you could help to address the issue. Thanks. Mostafa

**Comment by MOdabaee** [comment]
Hi, I just found out I used 32bit file and that's why I got errors in table generation.
Would you please provide 64 bit generator.exe?
Thanks.

**Comment by sebastian-90** [comment]
Hi Sanghera. I downloaded simplyfortran and created a project file with the code you supply here. In addition to this I loaded the fluids .FLDs from my REFPROPmini location as well as all the .DLLs from the REFPROPmini location. When compiling I obtain errors, namely: Error(E42): Last command making (taget.exe) returned bad status and Error(E02): Make execution terminated. I have very little experience with FORTRAN so I would be eternally grateful if you could advise me what I might be doing wrong.

**Comment by Sanghera** [comment]
Hey sebastian, sorry I don't really have FORTRAN setup on my computer anymore so I can't maintain this repo any longer. It could really be a number of things, but I used to use a program Simply Fortran to compile etc. Maybe try with that and see how it goes?

**Comment by sangheraio** [comment]
@MOdabaee Sorry I don't really have FORTRAN setup on my computer any longer so I wouldn't be able to do that.
@sebastian-90 It could really be a number of things, but I used to use a program called Simply Fortran when compiling. Maybe you could try that and see how it goes...

**Comment by sebastian-90** [comment]
@Sanghera I have tried this with Simply Fortran and without using the REFPROPmini files I have errors calling for missing variables. When I put all the installation files in the project, all the files start to compile and eventually return the previously mentioned errors. 

I have another code for converting REFPROP to RGP tables (from ANSYS support) but, due to my lack of experience in FORTRAN, I don't know how to interface the REFPROP variables with the code. I believe I need to make my source code talk to some .dll library? Any advice?

**Comment by sangheraio** [comment]
@sebastian-90 Yes you will need to purchase a copy of REFPROP and drop the fluid dll files into the fluids folder. It's licensed by NIST so unfortunately I can't provide them in this repo, otherwise I would have.
